import type { Metadata } from 'next'
import './globals.css'
import NavBar from '@/components/NavBar/NavBar'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ 
  subsets: ['latin'],
  weight: '400' 
})

export const metadata: Metadata = {
  title: 'Booksify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
